{% set version = "2.10.6" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rsm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rsm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rsm/rsm_{{ version }}.tar.gz
  sha256: d276a933c1641fedbc8023a21ab86a3c7a7e2e31b6e0b71b8525cd810b4bbfff

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-estimability
  run:
    - r-base
    - r-estimability

test:
  commands:
    - $R -e "library('rsm')"           # [not win]
    - "\"%R%\" -e \"library('rsm')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=rsm
  license: GPL-2.0-or-later
  summary: 'Provides functions to generate response-surface designs,  fit first- and second-order response-surface models,  make surface plots, obtain the path of steepest ascent,  and do canonical analysis. A good reference on these methods  is Chapter 10 of Wu, C-F J and Hamada, M (2009)  "Experiments: Planning, Analysis,
    and Parameter Design Optimization" ISBN 978-0-471-69946-0.'
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
