{% set version = '2.10' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rsm
  version: {{ version|replace("-", "_") }}

source:
  fn: rsm_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/rsm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rsm/rsm_{{ version }}.tar.gz
  sha256: 8c565b870d13801554582fc1ca72889c7dceed155be2172d05a4290c56eecb28

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1000
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-estimability
  run:
    - r-base
    - r-estimability

test:
  commands:
    - $R -e "library('rsm')"           # [not win]
    - "\"%R%\" -e \"library('rsm')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=rsm
  license: GPL (>= 2)
  summary: 'Provides functions to generate response-surface designs,  fit first- and second-order
    response-surface models,  make surface plots, obtain the path of steepest ascent,  and
    do canonical analysis. A good reference on these methods  is Chapter 10 of Wu, C-F
    J and Hamada, M (2009)  "Experiments: Planning, Analysis, and Parameter Design Optimization"
    ISBN 978-0-471-69946-0.'
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
