travis:
  secure:
    BINSTAR_TOKEN: 2/Kw8H0si7t6dEKx5aZES/IzQCnASCeFmRY9eYivl0GcprNemuGcox3OuvsEd2azqUsXnuOkjHBKQUO2QjqkFjEynAb9pFLHLL0/ASN/tDxOKZe4HE9JQ5I5gbeNGRRFLGEBO/vayYv8H6TfPysikscyymmQREugHWFXbtytDiOORBSwpo6jDS+jeWqvluyhlP/ZwURy9PqvkPTckcQIwQnkSaZYIypb4uVaisg7VmdEcShymFA2rilq9bUqLo7CNVhVKJQWUnr4h7W9/gl7OMG6mSRKAp3Z4jsA5c7Cv5S98kDldYB5HeirFYzWTO8kDEtUiwED5M41manxDHGc1machNrZNz5DuHrB1J3i/JU0IWrY/83K6/DiOs5AaP60F+GepDzogwrIoZhRMI+R8ubJkqAeaQGVpb0wFzErcCo31B2TBP8hTpgLF+LdgJVZBkZUWA/GDtPVx5S7pc7IcxH5L1atu1AvnwYB0crmJQ+PWLENq/ygjiB5HlC3JwsIXdAMQKcKrjnG6K7MGZjkAHk0g8yghZT42vvo9Rnw6Pf5v0ZsPYMDzK5xikLNyAKwNr3uEtWg/zLycc3cicW1dWP4fRWqFb1RQkYx/wsFuqcNKI9Hv7xlTZM01B10Q8ZVlREHY8uzie8y5EpQTL4fOsFOEocBYvCEc40q84IcsAk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
