travis:
  secure:
    BINSTAR_TOKEN: BqtTwbXfzuz4kOxeGlQ2kp6r4xY1/hKPr3GxSzef3Tj891OHmmLlW3dD0itHQ1ZW+mosf8irl4S4vnRO8EP7PRA1x+LrYIhLEFI26Ftcd5EHiErZv0agW14PMXc3rIpBjlMYMaPAQ1WVePVGsdYLhIVPnGVdiQFlAWyxr+SX3GMrouPd9peOTbOq5MvsHbvZybcCouhu5HKtg6SrDRD0hHzUQ2xLlrXAuu/eO0VYYoJw8w1WhXNniaZJlr5nOtvgNtF4ynJqtY/+4j7P4g93mDpnmceNFJMJbUc0szrhEvbKOpNUJOBM6mcjzV4PpBODUopJrJ9PyJdPWxFlgNaZw8iSqY3sY0aGNqkg3HSUTWC8rmL+7OhTTpTQ4HR6xEMcAcJs5zEEAePINne7vW0jCD9rWd/CvAMEZyp4F01EtK8cktNJkMjo3nDbLjsO39ORkEOmW/25cCgKwIJPjwTp7m3ssFJOzTx6IXmWBTE/6pHuddy0g1S145GWB+HcNeZbAHWSZUfUzoIAW47RepSCqc9SQRGRFnDrOBFp8NRefKvCCJimBeQbpKm21tP9yHjWwagUlOL0cI/XoLejsdCIa5LATS5me+dKCWToIa0qSQjHZ0zz+Ad5Emb84f4RgxouutqTaAKFa/2BQoGU+V2jw5za7Kb+YMtO7FTHBY8xr/0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
